name: "📚 Blog Updater"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs Every Day

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📚  Hashnode Updater"
        uses: "varunsridharan/action-hashnode-blog@main"
        with:
          USERNAME: "ivelle" # Hashnode Username
          BLOG_URL: "https://fosspill.opscyber.xyz/" # Blog URL
          COUNT: 3 # MAX Visible
          STYLE: "blog-alternate"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
